### PR TITLE
Verify  with test stabilization

### PR DESCRIPTION
**Pull request by lindycoder**

### CODE REVIEW

**Comment by lindycoder** [comment]
wait for @rocketb to see if we merge this or update his PR #8

**Review by true3HAK — APPROVED** [review]
So, now it's python 3+ only?
I'll not miss old one, but maybe, it needs to update readme for the project.

**Comment by lindycoder** [comment]
@true3HAK Only the bump dependencies tox target that runs pip tools is in python3, the whole tool is still tested with 

```
[tox]
envlist = py27,py34,py35,py36,lint
```

**Comment by lindycoder** [comment]
But thanks for the reminder i think i'll clean and merge this

**Review by ghost — APPROVED** [review]

**Pull request merged**
